all: glms

glms: 01-glms.Rmd
	Rscript -e 'rmarkdown::render("01-glms.Rmd")'

gams: 02-gams.Rmd
	Rscript -e 'rmarkdown::render("02-gams.Rmd")'

mixmod: 03-mixed-models.Rmd
	Rscript -e 'rmarkdown::render("03-mixed-models.Rmd")'
