all: intro learningR linmods

intro: 01-intro.Rmd
	Rscript -e 'rmarkdown::render("01-intro.Rmd")'

learningR: 02-learning-r.Rmd
	Rscript -e 'rmarkdown::render("02-learning-r.Rmd")'

linmods: 03-linear-models.Rmd
	Rscript -e 'rmarkdown::render("03-linear-models.Rmd")'
